source 'https://gems.ruby-china.org/'

gem 'rails', '4.2.6'
gem 'sass-rails', '5.0.4'
gem 'uglifier', '3.0.0'
gem 'coffee-rails', '4.1.1'
gem 'jquery-rails', '4.1.1'
gem 'bootstrap-sass',  '3.3.6'
gem 'turbolinks', '2.5.3'
gem 'jbuilder', '2.5.0'
gem 'guard-minitest', '2.4.5'
gem 'spork', '0.9.2'
gem 'sdoc', '0.4.1', group: :doc

group :development do
  gem 'byebug', '9.0.5'
  gem 'web-console', '2.3.0'
  gem 'spring', '1.7.1'
  gem 'sqlite3', '1.3.11'
end

group :test do
  gem 'minitest-reporters', '1.1.9'
  gem 'mini_backtrace', '0.1.3'
  gem 'guard', '2.14.0'
  gem 'guard-minitest', '2.4.5'
end

group :production do
  gem 'pg', '0.18.4'
  gem 'rails_12factor', '0.0.2'
end
